version: "3.8"

services:
  db:
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skarbonka
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3305:3306"
    networks:
      - my_network
      
  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: skarbonka
    ports:
     - "8000:8000"
    networks:
      - my_network

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - my_network
      
networks:
  my_network:
    driver: bridge