version: "3.8"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root # Root password for MySQL
      MYSQL_DATABASE: skarbonka # Name of the database to be created
      MYSQL_USER: user # Non-root user
      MYSQL_PASSWORD: user # Password for the non-root user
    ports:
      - "3307:3306" # Expose port 3307
    volumes:
      - db_data:/var/lib/mysql # Persist data in a Docker volume
      - ./database/skarbonka.sql:/docker-entrypoint-initdb.d/skarbonka.sql  # Mount the SQL file

volumes:
  db_data:
